version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: techlog-mongodb-dev
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - techlog-dev-network

volumes:
  mongodb_dev_data:

networks:
  techlog-dev-network:
    driver: bridge
